import type { Metadata } from "next";
import AppShell from "@/components/layout/AppShell";
import FloatingNav from "@/components/layout/FloatingNav";
import GlobalAssistant from "@/components/layout/GlobalAssistant";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppShell>
          {children}
        </AppShell>
        <FloatingNav />
        <GlobalAssistant />
      </body>
    </html>
  );
}
